***First Cell: Libraries***

In [1]:
import numpy as np
import pandas as pd

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)
print("Libraries imported successfully!")

NumPy version: 2.1.3
Pandas version: 2.2.3
Libraries imported successfully!

***Dataset***

In [2]:
data = {
    "Student_ID": [
        "ST001","ST002","ST003","ST004","ST005",
        "ST006","ST007","ST008","ST009","ST010",
        "ST011","ST012","ST013","ST014","ST015",
        "ST016","ST017","ST018","ST019","ST020"
    ],

    "Name": [
        "Aarav Sharma","Priya Verma","Rahul Singh","Ananya Gupta",
        "Rohan Kumar","Neha Patel","Vikash Yadav","Sneha Das",
        "Aditya Roy","Kavya Mishra","Aman Khan","Ishita Jain",
        "Mohit Sahu","Simran Kaur","Karan Mehta","Pooja Sharma",
        "Nitin Verma","Muskan Gupta","Harsh Tiwari","Riya Singh"
    ],

    "Department": ["CSE-AIML"] * 20,

    "Python": [
        78,92,65,84,55,88,42,76,69,95,
        58,81,73,64,49,87,61,79,91,68
    ],

    "NumPy": [
        85,89,72,81,61,93,48,79,66,91,
        54,86,71,63,44,82,59,77,88,75
    ],

    "Pandas": [
        74,95,68,79,58,85,51,83,72,93,
        62,80,69,67,46,90,64,82,89,70
    ],

    "Statistics": [
        88,90,70,86,64,91,45,75,68,96,
        57,84,77,61,52,85,63,80,92,73
    ],

    "Data_Analysis": [
        82,94,64,88,60,87,39,81,74,90,
        60,82,75,65,41,89,58,76,93,69
    ],

    "Attendance": [
        91,96,78,89,72,95,67,88,80,98,
        70,92,85,76,68,94,74,86,97,83
    ]
}

df = pd.DataFrame(data)

print("Dataset created successfully!")
print("Total students:", len(df))

df.head()

Dataset created successfully!
Total students: 20

,Student_ID,Name,Department,Python,NumPy,Pandas,Statistics,Data_Analysis,Attendance
0,ST001,Aarav Sharma,CSE-AIML,78,85,74,88,82,91
1,ST002,Priya Verma,CSE-AIML,92,89,95,90,94,96
2,ST003,Rahul Singh,CSE-AIML,65,72,68,70,64,78
3,ST004,Ananya Gupta,CSE-AIML,84,81,79,86,88,89
4,ST005,Rohan Kumar,CSE-AIML,55,61,58,64,60,72

***Dataset check***

In [3]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

Number of rows: 20
Number of columns: 9

Column Names:
['Student_ID', 'Name', 'Department', 'Python', 'NumPy', 'Pandas', 'Statistics', 'Data_Analysis', 'Attendance']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Student_ID     20 non-null     object
 1   Name           20 non-null     object
 2   Department     20 non-null     object
 3   Python         20 non-null     int64
 4   NumPy          20 non-null     int64
 5   Pandas         20 non-null     int64
 6   Statistics     20 non-null     int64
 7   Data_Analysis  20 non-null     int64
 8   Attendance     20 non-null     int64
dtypes: int64(6), object(3)
memory usage: 1.5+ KB

***Subjects define***

In [4]:
subjects = [
    "Python",
    "NumPy",
    "Pandas",
    "Statistics",
    "Data_Analysis"
]

print("Subjects:", subjects)

Subjects: ['Python', 'NumPy', 'Pandas', 'Statistics', 'Data_Analysis']

***Total Marks Function***

In [5]:
def calculate_total(marks):
    return int(np.sum(marks))

In [6]:
marks = [78, 85, 74, 88, 82]

print("Total Marks:", calculate_total(marks))

Total Marks: 407

***Average Function***

In [7]:
def calculate_average(marks):
    return round(float(np.mean(marks)), 2)

In [8]:
print("Average Marks:", calculate_average(marks))

Average Marks: 81.4

***Grade Function***

In [9]:
def assign_grade(average):

    if average >= 90:
        return "A+"

    elif average >= 80:
        return "A"

    elif average >= 70:
        return "B"

    elif average >= 60:
        return "C"

    elif average >= 50:
        return "D"

    else:
        return "F"

In [10]:
print(assign_grade(93))
print(assign_grade(81))
print(assign_grade(65))

A+
A
C

***Pass/Fail Function***

In [11]:
def check_pass(marks, attendance):

    for mark in marks:

        if mark < 40:
            return "Fail"

    if attendance < 75:
        return "Fail"

    return "Pass"

In [12]:
print(check_pass([78,85,74,88,82], 91))
print(check_pass([55,61,58,64,60], 72))

Pass
Fail

***Student Processing***

In [13]:
totals = []
averages = []
grades = []
results = []

for index, row in df.iterrows():

    marks = [
        row["Python"],
        row["NumPy"],
        row["Pandas"],
        row["Statistics"],
        row["Data_Analysis"]
    ]

    total = calculate_total(marks)
    average = calculate_average(marks)
    grade = assign_grade(average)
    result = check_pass(marks, row["Attendance"])

    totals.append(total)
    averages.append(average)
    grades.append(grade)
    results.append(result)

***Result added in data frame***

In [14]:
df["Total"] = totals
df["Average"] = averages
df["Grade"] = grades
df["Result"] = results

df.head()

,Student_ID,Name,Department,Python,NumPy,Pandas,Statistics,Data_Analysis,Attendance,Total,Average,Grade,Result
0,ST001,Aarav Sharma,CSE-AIML,78,85,74,88,82,91,407,81.4,A,Pass
1,ST002,Priya Verma,CSE-AIML,92,89,95,90,94,96,460,92.0,A+,Pass
2,ST003,Rahul Singh,CSE-AIML,65,72,68,70,64,78,339,67.8,C,Pass
3,ST004,Ananya Gupta,CSE-AIML,84,81,79,86,88,89,418,83.6,A,Pass
4,ST005,Rohan Kumar,CSE-AIML,55,61,58,64,60,72,298,59.6,D,Fail

**Total**
**Average**
**Grade**
**Result**

***Complete Student Performance***

In [15]:
student_performance = df[
    [
        "Student_ID",
        "Name",
        "Total",
        "Average",
        "Grade",
        "Attendance",
        "Result"
    ]
]

student_performance

   Student_ID          Name  Total  Average Grade  Attendance Result
0       ST001  Aarav Sharma    407     81.4     A          91   Pass
1       ST002   Priya Verma    460     92.0    A+          96   Pass
2       ST003   Rahul Singh    339     67.8     C          78   Pass
3       ST004  Ananya Gupta    418     83.6     A          89   Pass
4       ST005   Rohan Kumar    298     59.6     D          72   Fail
5       ST006    Neha Patel    444     88.8     A          95   Pass
6       ST007  Vikash Yadav    225     45.0     F          67   Fail
7       ST008     Sneha Das    394     78.8     B          88   Pass
8       ST009    Aditya Roy    349     69.8     C          80   Pass
9       ST010  Kavya Mishra    465     93.0    A+          98   Pass
10      ST011     Aman Khan    291     58.2     D          70   Fail
11      ST012   Ishita Jain    413     82.6     A          92   Pass
12      ST013    Mohit Sahu    365     73.0     B          85   Pass
13      ST014   Simran Kaur    320     64.0     C          76   Pass
14      ST015   Karan Mehta    232     46.4     F          68   Fail
15      ST016  Pooja Sharma    433     86.6     A          94   Pass
16      ST017   Nitin Verma    305     61.0     C          74   Fail
17      ST018  Muskan Gupta    394     78.8     B          86   Pass
18      ST019  Harsh Tiwari    453     90.6    A+          97   Pass
19      ST020    Riya Singh    355     71.0     B          83   Pass

***Class Average***

In [16]:
class_average = df["Average"].mean()

print("Overall Class Average:", round(class_average, 2))

Overall Class Average: 73.6

***Highest Performer***

In [17]:
highest_student = df.loc[df["Average"].idxmax()]

print("Highest Performing Student:")
print("Name:", highest_student["Name"])
print("Average:", highest_student["Average"])
print("Grade:", highest_student["Grade"])

Highest Performing Student:
Name: Kavya Mishra
Average: 93.0
Grade: A+

***Lowest Performer***

In [18]:
lowest_student = df.loc[df["Average"].idxmin()]

print("Lowest Performing Student:")
print("Name:", lowest_student["Name"])
print("Average:", lowest_student["Average"])
print("Grade:", lowest_student["Grade"])

Lowest Performing Student:
Name: Vikash Yadav
Average: 45.0
Grade: F

***Pass/Fail Statistics***

In [19]:
pass_count = (df["Result"] == "Pass").sum()
fail_count = (df["Result"] == "Fail").sum()

print("Total Students:", len(df))
print("Passed Students:", pass_count)
print("Failed Students:", fail_count)

Total Students: 20
Passed Students: 15
Failed Students: 5

***Subject-wise Analysis***

In [20]:
subject_analysis = []

for subject in subjects:

    subject_analysis.append({
        "Subject": subject,
        "Average": round(df[subject].mean(), 2),
        "Highest": df[subject].max(),
        "Lowest": df[subject].min()
    })

subject_df = pd.DataFrame(subject_analysis)

subject_df

         Subject  Average  Highest  Lowest
0         Python    72.75       95      42
1          NumPy    73.20       93      44
2         Pandas    73.85       95      46
3     Statistics    74.85       96      45
4  Data_Analysis    73.35       94      39

***Best Subject***

In [21]:
best_subject = subject_df.loc[
    subject_df["Average"].idxmax()
]

print("Best Subject:", best_subject["Subject"])
print("Average Marks:", best_subject["Average"])

Best Subject: Statistics
Average Marks: 74.85

***Top 3 Students***

In [22]:
# Ensure calculations are assigned to df before sorting
df["Total"] = totals
df["Average"] = averages
df["Grade"] = grades
df["Result"] = results

top_3 = df.sort_values(
    by="Average",
    ascending=False
).head(3)

top_3[
    ["Student_ID", "Name", "Average", "Grade"]
]

   Student_ID          Name  Average Grade
9       ST010  Kavya Mishra     93.0    A+
1       ST002   Priya Verma     92.0    A+
18      ST019  Harsh Tiwari     90.6    A+

***Final Dashboard-style Summary***

In [23]:
print("=" * 60)
print("       STUDENT PERFORMANCE ANALYTICS SYSTEM")
print("=" * 60)

print("Total Students:", len(df))
print("Class Average:", round(df["Average"].mean(), 2))
print("Highest Average:", df["Average"].max())
print("Lowest Average:", df["Average"].min())

print("Passed:", (df["Result"] == "Pass").sum())
print("Failed:", (df["Result"] == "Fail").sum())

print("\nTop Performer:")
top = df.loc[df["Average"].idxmax()]
print(top["Name"], "-", top["Average"], "-", top["Grade"])

print("\nBest Subject:")
best = subject_df.loc[subject_df["Average"].idxmax()]
print(best["Subject"], "-", best["Average"])

print("=" * 60)

============================================================
       STUDENT PERFORMANCE ANALYTICS SYSTEM
============================================================
Total Students: 20
Class Average: 73.6
Highest Average: 93.0
Lowest Average: 45.0
Passed: 15
Failed: 5

Top Performer:
Kavya Mishra - 93.0 - A+

Best Subject:
Statistics - 74.85
============================================================